services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      QDRANT_URL: qdrant
      QDRANT_PORT: 6333
      QDRANT_COLLECTION_NAME: ${QDRANT_COLLECTION_NAME}
      PDF_DATA_PATH: ${PDF_DATA_PATH}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_EMBEDDING_DEPLOYMENT: ${AZURE_OPENAI_EMBEDDING_DEPLOYMENT}
      AZURE_OPENAI_CHAT_DEPLOYMENT: ${AZURE_OPENAI_CHAT_DEPLOYMENT}
      VECTOR_SIZE: ${VECTOR_SIZE}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "80:8000"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334

    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
